env:
  es6: true
  amd: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
globals:
  module: true
plugins:
  - react
rules:
  no-console: "off"
  no-unused-vars: "off"
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
